# Generated by Django 3.0.1 on 2019-12-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='end_time',
            field=models.TimeField(null=True),
        ),
    ]
