# Generated by Django 3.0.1 on 2019-12-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191221_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='type',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff',
            name='name',
            field=models.CharField(max_length=45),
        ),
    ]
