# Generated by Django 3.0.1 on 2019-12-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191222_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstate',
            name='num_of_login',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userstate',
            name='tot_time_spend',
            field=models.IntegerField(null=True),
        ),
    ]
