# Generated by Django 3.0.1 on 2019-12-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191223_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstate',
            name='num_of_login',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userstate',
            name='tot_time_spend',
            field=models.IntegerField(default=0),
        ),
    ]
