# Generated by Django 3.0.1 on 2019-12-22 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20191221_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.FileField(upload_to=''),
        ),
    ]
